use crate::e10::e10;
use crate::e11::e11;
use crate::e12::e12;
use crate::e13::e13;
use crate::e14::e14;
use crate::e15::e15;

mod e1;
mod e2;
mod e3;
mod e4;
mod e5;
mod e6;
mod e7;
mod e8;
mod e9;
mod e10;
mod e11;
mod e12;
mod e13;
mod util;
mod e14;
mod e15;

fn main() {
    // let (value, exec_time) = e1();
    // println!("problem 1 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e2();
    // println!("problem 2 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e3();
    // println!("problem 3 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e4();
    // println!("problem 4 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e5();
    // println!("problem 5 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e6();
    // println!("problem 6 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e7();
    // println!("problem 7 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e8();
    // println!("problem 8 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e9();
    // println!("problem 9 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e10();
    // println!("problem 10 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e11();
    // println!("problem 11 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e12();
    // println!("problem 12 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e13();
    // println!("problem 13 returned {} in {} ns", value, exec_time);
    // let (value, exec_time) = e14();
    // println!("problem 14 returned {} in {} ns", value, exec_time);
    let (value, exec_time) = e15();
    println!("problem 15 returned {} in {} ns", value, exec_time);
}
