

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.
public class J2 {
    public static void main(String[] args) {
        int FirstTerm = 0;
        int SecondTerm = 1;
        int nextTerm = 0;
        int count = 0;
        while(nextTerm<4000000) {
            nextTerm = FirstTerm + SecondTerm;
            FirstTerm = SecondTerm;
            SecondTerm = nextTerm;
            if(FirstTerm%2==0){
                count+=FirstTerm;
            }
        }
        System.out.println(count);
        
    }
}
