#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?

def NumberOfFactors(Number):
    NumberOfFactor = 0
    for i in range(1, int(Number**(1/2))):
        if Number % i == 0:
            NumberOfFactor +=2
    if Number**(1/2) == int(Number**(1/2)) :
        NumberOfFactor +=1
    return NumberOfFactor

i = 1
TriangularNumber = 0

Found = False
while not Found:
    TriangularNumber +=i
    nof=NumberOfFactors(TriangularNumber)
    if nof > 500:
        Found = True
        print(TriangularNumber, nof)
    i+=1





